+++
title = "Python3 的异常处理"
postid = 2143
date = 2014-08-14T09:53:27+08:00
isCJKLanguage = true
toc = false
type = "post"
slug = "exception_in_python3"
aliases = [ "/post/2143.html",]
category = [ "technology",]
tag = [ "python",]
+++


[Python3 的异常处理](https://blog.zengrong.net/post/2143.html)

Exception in Python3.

Python3 的异常处理，在官方文档的 [tutorial][1] 中有说明。

这里把常用的异常处理方法都列出来，方便平时查找。

# 捕获异常基类

Python3 要求我们的异常必须继承 Exception 类。Built-in 的所有异常也都是继承自这个类。因此，我们只需要捕获这个类的实例，就可以捕获所有的异常。

``` python
try:
	raise
except Exception as err:
	print(err)
```

<!--more-->

# 使用 sys.exc_info() 和 sys.last_traceback

`sys.exc_info()` 会返回一个3值元表，其中包含调用该命令时捕获的异常。

这个元表的内容为 (type, value, traceback) ，其中：

* type 从获取到的异常中得到类型名称，它是BaseException 的子类；
* value 是捕获到的异常实例；
* traceback 是一个 traceback 对象，下面会详述。

`sys.last_traceback` 包含的内容与 `sys.exc_info()` 相同，但它主要用于调试，并不总是被定义。

``` python
import sys
try:
	raise
except:
	t,v,tb = sys.exc_info()
	print(t,v)
```

# 使用 traceback

trackback 模块用来精确模仿 python3 解析器的 stack trace 行为。在程序中应该尽量使用这个模块。

`traceback.print_exc()` 可以直接打印当前的异常。

``` python
import traceback
try:
	raise
except:
	traceback.print_exc()
```

`traceback.print_tb()` 用来打印上面提到的 trackback 对象。

``` python
import sys,traceback
try:
	raise
except:
	t,v,tb = sys.exc_info()
	traceback.print_tb(tb)
```

`traceback.print_exception()` 可以直接打印 `sys.exc_info()` 提供的元表。

``` python
import sys,traceback
try:
	raise
except:
	traceback.print_exception(*sys.exc_info())
```

其实，下面两句是等价的：

* `traceback.print_exc()`
* `traceback.print_exception(*sys.exc_info())`

traceback 提供的参数可以将 print 的内容写入到文件中，详见这里：[29.9. traceback — Print or retrieve a stack traceback][2]

[1]: https://docs.python.org/3/tutorial/errors.html
[2]: https://docs.python.org/3/library/traceback.html?highlight=print_tb#traceback.print_exc
